import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getReport } from '../services/api';
import IntelReport from '../components/IntelReport';

export default function SharedReport() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [report, setReport] = useState(null);
  const [status, setStatus] = useState('loading'); // 'loading' | 'ready' | 'not-found'

  useEffect(() => {
    document.title = 'myagent.fyi — Shared report';
  }, []);

  useEffect(() => {
    getReport(id)
      .then((data) => {
        setReport(data);
        setStatus('ready');
      })
      .catch(() => setStatus('not-found'));
  }, [id]);

  return (
    <div className="shared-report">
      <header className="shared-report-topbar">
        <button className="topbar-brand" onClick={() => navigate('/')}>
          myagent<span className="accent">.fyi</span>
        </button>
      </header>

      <main className="shared-report-main">
        {status === 'loading' && (
          <p className="state-muted">Loading report...</p>
        )}

        {status === 'not-found' && (
          <p className="state-muted">This report doesn't exist or is no longer available.</p>
        )}

        {status === 'ready' && (
          <div className="intel-report-page">
            <div className="intel-report-toolbar">
              <h1 className="intel-report-company">{report.company_name}</h1>
            </div>
            <IntelReport data={report} />
          </div>
        )}
      </main>

      <footer className="shared-report-cta">
        <p className="shared-report-cta-text">
          Generated by <span className="accent">myagent.fyi</span>
        </p>
        <button className="btn-primary" onClick={() => navigate('/start')}>
          Activate your own agent →
        </button>
      </footer>
    </div>
  );
}
